name: ht_app_settings_repository
description: ...
repository: https://github.com/headlines-toolkit/ht-app-settings-repository
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies: 
  ht_app_settings_client:
    git:
      url: https://github.com/headlines-toolkit/ht-app-settings-client.git

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^7.0.0
