name: ht_app_settings_repository
description: A repository package for managing application settings (theme, language) built upon ht_app_settings_client.
repository: https://github.com/headlines-toolkit/ht-app-settings-repository
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies: 
  ht_app_settings_client:
    git:
      url: https://github.com/headlines-toolkit/ht-app-settings-client.git
  ht_shared:
    git:
      url: https://github.com/headlines-toolkit/ht-shared.git
  meta: ^1.16.0
  rxdart: ^0.28.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^7.0.0
